### ISSUE TITLE
Gem::GemNotFoundException

### ISSUE THREAD

**Issue by Tgo1014** [thefuntasty/bitrise-step-apk-info#13]
When I run the ApkInfo step I receive the following error:

```
+------------------------------------------------------------------------------+
| (1) Get App Info                                                             |
+------------------------------------------------------------------------------+
| id: apk-info                                                                 |
| version: 1.4.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-01-03T15:56:19Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.12.5) required by your /tmp/bitrise274759856/step_src/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.12.5`
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:294:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Get App Info (exit code: 1)                                   | 1.42 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/thefuntasty/bitrise-step-apk-info/issues   |
| Source: https://github.com/thefuntasty/bitrise-step-apk-info                 |
+---+---------------------------------------------------------------+----------+
```

**Comment by joekimnguyen** [comment]
I am also seeing this issue

**Comment by Tgo1014** [comment]
A valid workaround at moment is adding this step before the the ApkInfo step:

```
    - script@1.1.5:
        inputs:
        - content: gem install bundler:1.12.5
```

**Comment by skywall** [comment]
Thank you for report and sorry for the late response. I'll take a look at it.

**Comment by Tgo1014** [comment]
Thank you for fixing the issue @skywall but the step update is not yet available at bitrise. Do you have any idea when it's going to be available? 

Thank you!

**Comment by skywall** [comment]
@Tgo1014 Today.

Edit: https://github.com/bitrise-io/bitrise-steplib/pull/2447

**Comment by skywall** [comment]
I have reopened the issue to track progress easily.

**Comment by Tgo1014** [comment]
Thanks, but looks like they still didn't approve your change for the step to be available.

**Comment by skywall** [comment]
@Tgo1014 They've just merged it. Can you please check if the fix works for you?

**Comment by Tgo1014** [comment]
@skywall Sorry! I just had time to test it today. Working perfectly. Thank you for the fix!
